server:
  port: 8999
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    port-header: X-Forwarded-Port
  use-forward-headers: true
  servlet:
    session:
      #24*60*60=
      timeout: 86400

spring:
  application:
    name: crm-boss
  profiles:
    active: local

img:
  local:
    path:
  host:

logging:
  file: ./log/${spring.application.name}.log








